POST http://localhost:7077/users/create
Content-Type: application/json

{
    "Avatar": "https://newmartina.it/cdn/shop/files/DDS02039_6196f34f-e1a3-4810-9d6f-87e33489535c.jpg?v=1687180444&width=2048",
    "FirstName": "Gianni",
    "LastName": "Fantoni",
    "Email": "fantoni@example.com",
    "Password": "giannifantoni",
    "Role": "user"
}

####

GET http://localhost:7077/users

####

DELETE http://localhost:7077/users/DELETE/654127310e4b22c22f28b944

####

PATCH http://localhost:7077/users/edit/6541056c715b1312b0dcd950
Content-Type: application/json

{
    "Avatar": "https://newmartina.it/cdn/shop/files/DDS02039_6196f34f-e1a3-4810-9d6f-87e33489535c.jpg?v=1687180444&width=2048",
    "FirstName": "Giuseppe",
    "LastName": "Fantoni",
    "Email": "fantoni@example.com",
    "Password": "giannifantoni",
    "Role":"user"
}

####

GET http://localhost:7077/users/byId/653a59a53eae50bd5c5fc678

####

POST http://localhost:7077/login
Content-Type: application/json

{
    "Email": "fantoni@example.com",
    "Password" :"giannifantoni"
}